@startuml
== Tara ==
task_tare -> task_wait
activate task_tare
group Medicion de fuerza con promedio
activate task_wait
task_wait -> task_measurement : sem_measurement
deactivate task_wait
loop 15 veces
activate task_measurement
task_measurement -> task_average : queue_measurement
activate task_average
task_measurement <- task_average : sem_measurement
deactivate task_measurement
end
end
task_average -> task_tare : queue_force
deactivate task_average
== ==
task_tare -> protocol_x_init
deactivate task_tare
group Recepcion wifi
activate protocol_x_init
protocol_x_init -> protocol_rx_event : uartCallbackSet
deactivate protocol_x_init
activate protocol_rx_event
protocol_rx_event -> wait_frame : new_frame_signal, mutex
deactivate protocol_rx_event
activate wait_frame
wait_frame -> protocol_transmit_frame 
deactivate wait_frame
activate protocol_transmit_frame
end
alt se recibio un 1
protocol_transmit_frame -> task_weight
activate task_weight
task_weight -> task_wait
group Medicion de fuerza con promedio
activate task_wait
task_wait -> task_measurement : sem_measurement
deactivate task_wait
loop 15 times
activate task_measurement
task_measurement -> task_average : queue_measurement
activate task_average
task_measurement <- task_average : sem_measurement
deactivate task_measurement
end
end 
task_average -> task_weight : queue_force
deactivate task_average
deactivate task_weight
task_weight -> protocol_x_init
group Recepcion wifi
activate protocol_x_init
protocol_x_init -> protocol_rx_event : uartCallbackSet
deactivate protocol_x_init
activate protocol_rx_event
protocol_rx_event -> wait_frame : new_frame_signal, mutex
deactivate protocol_rx_event
activate wait_frame
wait_frame -> protocol_transmit_frame 
end
deactivate wait_frame
else se recibio un 2
protocol_transmit_frame -> task_jump
activate task_jump
group Medicion de fuerza
loop hasta que la persona se despegue de la plataforma
task_jump -> task_measurement : sem_measurement
task_measurement -> task_jump : queue_force
end
end
task_jump -> protocol_x_init
deactivate task_jump
group Recepcion wifi
activate protocol_x_init
protocol_x_init -> protocol_rx_event : uartCallbackSet
deactivate protocol_x_init
activate protocol_rx_event
protocol_rx_event -> wait_frame : new_frame_signal, mutex
deactivate protocol_rx_event
activate wait_frame
wait_frame -> protocol_transmit_frame 
deactivate wait_frame
end
deactivate protocol_transmit_frame
end
@enduml